package alias

import "github.com/reusee/domui"

// https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes

func makeAttrFunc(name string) func(value any) domui.AttrsSpec {
	return func(value any) domui.AttrsSpec {
		return domui.AttrsSpec{
			Attrs: map[string]any{
				name: value,
			},
		}
	}
}

var (
	AAccept          = makeAttrFunc("accept")
	AAcceptCharset   = makeAttrFunc("accept-charset")
	AAccesskey       = makeAttrFunc("accesskey")
	AAction          = makeAttrFunc("action")
	AAlign           = makeAttrFunc("align")
	AAllow           = makeAttrFunc("allow")
	AAlt             = makeAttrFunc("alt")
	AAsync           = makeAttrFunc("async")
	AAutocapitalize  = makeAttrFunc("autocapitalize")
	AAutocomplete    = makeAttrFunc("autocomplete")
	AAutofocus       = makeAttrFunc("autofocus")
	AAutoplay        = makeAttrFunc("autoplay")
	ABackground      = makeAttrFunc("background")
	ABgcolor         = makeAttrFunc("bgcolor")
	ABorder          = makeAttrFunc("border")
	ABuffered        = makeAttrFunc("buffered")
	ACapture         = makeAttrFunc("capture")
	AChallenge       = makeAttrFunc("challenge")
	ACharset         = makeAttrFunc("charset")
	AChecked         = makeAttrFunc("checked")
	ACite            = makeAttrFunc("cite")
	AClass           = makeAttrFunc("class")
	ACode            = makeAttrFunc("code")
	ACodebase        = makeAttrFunc("codebase")
	AColor           = makeAttrFunc("color")
	ACols            = makeAttrFunc("cols")
	AColspan         = makeAttrFunc("colspan")
	AContent         = makeAttrFunc("content")
	AContenteditable = makeAttrFunc("contenteditable")
	AContextmenu     = makeAttrFunc("contextmenu")
	AControls        = makeAttrFunc("controls")
	ACoords          = makeAttrFunc("coords")
	ACrossorigin     = makeAttrFunc("crossorigin")
	ACsp             = makeAttrFunc("csp")
	AData            = makeAttrFunc("data")
	ADatetime        = makeAttrFunc("datetime")
	ADecoding        = makeAttrFunc("decoding")
	ADefault         = makeAttrFunc("default")
	ADefer           = makeAttrFunc("defer")
	ADir             = makeAttrFunc("dir")
	ADirname         = makeAttrFunc("dirname")
	ADisabled        = makeAttrFunc("disabled")
	ADownload        = makeAttrFunc("download")
	ADraggable       = makeAttrFunc("draggable")
	AEnctype         = makeAttrFunc("enctype")
	AEnterkeyhint    = makeAttrFunc("enterkeyhint")
	AFor             = makeAttrFunc("for")
	AForm            = makeAttrFunc("form")
	AFormaction      = makeAttrFunc("formaction")
	AFormenctype     = makeAttrFunc("formenctype")
	AFormmethod      = makeAttrFunc("formmethod")
	AFormnovalidate  = makeAttrFunc("formnovalidate")
	AFormtarget      = makeAttrFunc("formtarget")
	AHeaders         = makeAttrFunc("headers")
	AHeight          = makeAttrFunc("height")
	AHidden          = makeAttrFunc("hidden")
	AHigh            = makeAttrFunc("high")
	AHref            = makeAttrFunc("href")
	AHreflang        = makeAttrFunc("hreflang")
	AHttpEquiv       = makeAttrFunc("http-equiv")
	AIcon            = makeAttrFunc("icon")
	AId              = makeAttrFunc("id")
	AImportance      = makeAttrFunc("importance")
	AInputmode       = makeAttrFunc("inputmode")
	AIntegrity       = makeAttrFunc("integrity")
	AIntrinsicsize   = makeAttrFunc("intrinsicsize")
	AIsmap           = makeAttrFunc("ismap")
	AItemprop        = makeAttrFunc("itemprop")
	AKeytype         = makeAttrFunc("keytype")
	AKind            = makeAttrFunc("kind")
	ALabel           = makeAttrFunc("label")
	ALang            = makeAttrFunc("lang")
	ALanguage        = makeAttrFunc("language")
	AList            = makeAttrFunc("list")
	ALoading         = makeAttrFunc("loading")
	ALoop            = makeAttrFunc("loop")
	ALow             = makeAttrFunc("low")
	AMax             = makeAttrFunc("max")
	AMaxlength       = makeAttrFunc("maxlength")
	AMedia           = makeAttrFunc("media")
	AMethod          = makeAttrFunc("method")
	AMin             = makeAttrFunc("min")
	AMinlength       = makeAttrFunc("minlength")
	AMultiple        = makeAttrFunc("multiple")
	AMuted           = makeAttrFunc("muted")
	AName            = makeAttrFunc("name")
	ANovalidate      = makeAttrFunc("novalidate")
	AOpen            = makeAttrFunc("open")
	AOptimum         = makeAttrFunc("optimum")
	APattern         = makeAttrFunc("pattern")
	APing            = makeAttrFunc("ping")
	APlaceholder     = makeAttrFunc("placeholder")
	APoster          = makeAttrFunc("poster")
	APreload         = makeAttrFunc("preload")
	ARadiogroup      = makeAttrFunc("radiogroup")
	AReadonly        = makeAttrFunc("readonly")
	AReferrerpolicy  = makeAttrFunc("referrerpolicy")
	ARel             = makeAttrFunc("rel")
	ARequired        = makeAttrFunc("required")
	AReversed        = makeAttrFunc("reversed")
	ARows            = makeAttrFunc("rows")
	ARowspan         = makeAttrFunc("rowspan")
	ASandbox         = makeAttrFunc("sandbox")
	AScope           = makeAttrFunc("scope")
	AScoped          = makeAttrFunc("scoped")
	ASelected        = makeAttrFunc("selected")
	AShape           = makeAttrFunc("shape")
	ASize            = makeAttrFunc("size")
	ASizes           = makeAttrFunc("sizes")
	ASlot            = makeAttrFunc("slot")
	ASpan            = makeAttrFunc("span")
	ASpellcheck      = makeAttrFunc("spellcheck")
	ASrc             = makeAttrFunc("src")
	ASrcdoc          = makeAttrFunc("srcdoc")
	ASrclang         = makeAttrFunc("srclang")
	ASrcset          = makeAttrFunc("srcset")
	AStart           = makeAttrFunc("start")
	AStep            = makeAttrFunc("step")
	AStyle           = makeAttrFunc("style")
	ASummary         = makeAttrFunc("summary")
	ATabindex        = makeAttrFunc("tabindex")
	ATarget          = makeAttrFunc("target")
	ATitle           = makeAttrFunc("title")
	ATranslate       = makeAttrFunc("translate")
	AType            = makeAttrFunc("type")
	AUsemap          = makeAttrFunc("usemap")
	AValue           = makeAttrFunc("value")
	AWidth           = makeAttrFunc("width")
	AWrap            = makeAttrFunc("wrap")
)
