package alias

import "github.com/reusee/domui"

// https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes

func makeAttrFunc(name string) func(value any) domui.AttrsSpec {
	return func(value any) domui.AttrsSpec {
		return domui.AttrsSpec{
			Attrs: map[string]any{
				name: value,
			},
		}
	}
}

var (
	Aaccept          = makeAttrFunc("accept")
	AacceptCharset   = makeAttrFunc("accept-charset")
	Aaccesskey       = makeAttrFunc("accesskey")
	Aaction          = makeAttrFunc("action")
	Aalign           = makeAttrFunc("align")
	Aallow           = makeAttrFunc("allow")
	Aalt             = makeAttrFunc("alt")
	Aasync           = makeAttrFunc("async")
	Aautocapitalize  = makeAttrFunc("autocapitalize")
	Aautocomplete    = makeAttrFunc("autocomplete")
	Aautofocus       = makeAttrFunc("autofocus")
	Aautoplay        = makeAttrFunc("autoplay")
	Abackground      = makeAttrFunc("background")
	Abgcolor         = makeAttrFunc("bgcolor")
	Aborder          = makeAttrFunc("border")
	Abuffered        = makeAttrFunc("buffered")
	Acapture         = makeAttrFunc("capture")
	Achallenge       = makeAttrFunc("challenge")
	Acharset         = makeAttrFunc("charset")
	Achecked         = makeAttrFunc("checked")
	Acite            = makeAttrFunc("cite")
	Aclass           = makeAttrFunc("class")
	Acode            = makeAttrFunc("code")
	Acodebase        = makeAttrFunc("codebase")
	Acolor           = makeAttrFunc("color")
	Acols            = makeAttrFunc("cols")
	Acolspan         = makeAttrFunc("colspan")
	Acontent         = makeAttrFunc("content")
	Acontenteditable = makeAttrFunc("contenteditable")
	Acontextmenu     = makeAttrFunc("contextmenu")
	Acontrols        = makeAttrFunc("controls")
	Acoords          = makeAttrFunc("coords")
	Acrossorigin     = makeAttrFunc("crossorigin")
	Acsp             = makeAttrFunc("csp")
	Adata            = makeAttrFunc("data")
	Adatetime        = makeAttrFunc("datetime")
	Adecoding        = makeAttrFunc("decoding")
	Adefault         = makeAttrFunc("default")
	Adefer           = makeAttrFunc("defer")
	Adir             = makeAttrFunc("dir")
	Adirname         = makeAttrFunc("dirname")
	Adisabled        = makeAttrFunc("disabled")
	Adownload        = makeAttrFunc("download")
	Adraggable       = makeAttrFunc("draggable")
	Aenctype         = makeAttrFunc("enctype")
	Aenterkeyhint    = makeAttrFunc("enterkeyhint")
	Afor             = makeAttrFunc("for")
	Aform            = makeAttrFunc("form")
	Aformaction      = makeAttrFunc("formaction")
	Aformenctype     = makeAttrFunc("formenctype")
	Aformmethod      = makeAttrFunc("formmethod")
	Aformnovalidate  = makeAttrFunc("formnovalidate")
	Aformtarget      = makeAttrFunc("formtarget")
	Aheaders         = makeAttrFunc("headers")
	Aheight          = makeAttrFunc("height")
	Ahidden          = makeAttrFunc("hidden")
	Ahigh            = makeAttrFunc("high")
	Ahref            = makeAttrFunc("href")
	Ahreflang        = makeAttrFunc("hreflang")
	AhttpEquiv       = makeAttrFunc("http-equiv")
	Aicon            = makeAttrFunc("icon")
	Aid              = makeAttrFunc("id")
	Aimportance      = makeAttrFunc("importance")
	Ainputmode       = makeAttrFunc("inputmode")
	Aintegrity       = makeAttrFunc("integrity")
	Aintrinsicsize   = makeAttrFunc("intrinsicsize")
	Aismap           = makeAttrFunc("ismap")
	Aitemprop        = makeAttrFunc("itemprop")
	Akeytype         = makeAttrFunc("keytype")
	Akind            = makeAttrFunc("kind")
	Alabel           = makeAttrFunc("label")
	Alang            = makeAttrFunc("lang")
	Alanguage        = makeAttrFunc("language")
	Alist            = makeAttrFunc("list")
	Aloading         = makeAttrFunc("loading")
	Aloop            = makeAttrFunc("loop")
	Alow             = makeAttrFunc("low")
	Amax             = makeAttrFunc("max")
	Amaxlength       = makeAttrFunc("maxlength")
	Amedia           = makeAttrFunc("media")
	Amethod          = makeAttrFunc("method")
	Amin             = makeAttrFunc("min")
	Aminlength       = makeAttrFunc("minlength")
	Amultiple        = makeAttrFunc("multiple")
	Amuted           = makeAttrFunc("muted")
	Aname            = makeAttrFunc("name")
	Anovalidate      = makeAttrFunc("novalidate")
	Aopen            = makeAttrFunc("open")
	Aoptimum         = makeAttrFunc("optimum")
	Apattern         = makeAttrFunc("pattern")
	Aping            = makeAttrFunc("ping")
	Aplaceholder     = makeAttrFunc("placeholder")
	Aposter          = makeAttrFunc("poster")
	Apreload         = makeAttrFunc("preload")
	Aradiogroup      = makeAttrFunc("radiogroup")
	Areadonly        = makeAttrFunc("readonly")
	Areferrerpolicy  = makeAttrFunc("referrerpolicy")
	Arel             = makeAttrFunc("rel")
	Arequired        = makeAttrFunc("required")
	Areversed        = makeAttrFunc("reversed")
	Arows            = makeAttrFunc("rows")
	Arowspan         = makeAttrFunc("rowspan")
	Asandbox         = makeAttrFunc("sandbox")
	Ascope           = makeAttrFunc("scope")
	Ascoped          = makeAttrFunc("scoped")
	Aselected        = makeAttrFunc("selected")
	Ashape           = makeAttrFunc("shape")
	Asize            = makeAttrFunc("size")
	Asizes           = makeAttrFunc("sizes")
	Aslot            = makeAttrFunc("slot")
	Aspan            = makeAttrFunc("span")
	Aspellcheck      = makeAttrFunc("spellcheck")
	Asrc             = makeAttrFunc("src")
	Asrcdoc          = makeAttrFunc("srcdoc")
	Asrclang         = makeAttrFunc("srclang")
	Asrcset          = makeAttrFunc("srcset")
	Astart           = makeAttrFunc("start")
	Astep            = makeAttrFunc("step")
	Astyle           = makeAttrFunc("style")
	Asummary         = makeAttrFunc("summary")
	Atabindex        = makeAttrFunc("tabindex")
	Atarget          = makeAttrFunc("target")
	Atitle           = makeAttrFunc("title")
	Atranslate       = makeAttrFunc("translate")
	Atype            = makeAttrFunc("type")
	Ausemap          = makeAttrFunc("usemap")
	Avalue           = makeAttrFunc("value")
	Awidth           = makeAttrFunc("width")
	Awrap            = makeAttrFunc("wrap")
)
